### ISSUE TITLE
HELP!!!    How do I make connection by localhost:6789

### ISSUE THREAD

**Issue by tristanwhh** [google/rappor#115]
No matter I type the command: ./run_app.sh [port] or ./run_app.sh, the connection cannot be made and the warning message is displayed on the terminal window.

Also, I check the directory carefully, all of them are correct.... But why do I still make some mistakes?

HELP!!!

**Comment by lilyhhha** [comment]
Hello, I also failed to display the link UI.R file on linux side after running the shiny webpage file. Could you please tell me if you have found the solution? Thanks!

**Comment by tristanwhh** [comment]
nothing
